name: Run Munster Match Bot Daily

on:
  schedule:
    - cron: '0 8 * * *'   # Every day at 08:00 UTC
  workflow_dispatch:       # Manual trigger option

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install praw requests beautifulsoup4

      - name: Run Munster bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: python munster_bot.py
