name: Archive Comment Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes (safer polling interval)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install praw requests

      - name: Run archive comment bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          SUBREDDIT_NAME: ${{ secrets.SUBREDDIT_NAME }}  # Optional: Add if parameterizing
          TARGET_USER: ${{ secrets.TARGET_USER }}        # Optional: Add if parameterizing
          TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}    # Optional: Add if parameterizing
          RUN_ONCE: true                                 # Ensures single pass per run
        run: python comment_archives.py
