name: Munster Match Thread Bot

on:
  schedule:
    - cron: "0 * * * *"  # Runs hourly to check for matches within 3 hours
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install praw requests beautifulsoup4 pytz

      - name: Run Munster Match Thread Bot
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USER_AGENT: "MunsterKickoffBot:v2.0 (by u/MunsterKickoff)"
        run: python munster_bot.py
